image: m.daocloud.io/docker.io/library/node:22-alpine

stages:
  - build

variables:
  NEXT_TELEMETRY_DISABLED: "1"

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

build:
  stage: build
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
