image: m.daocloud.io/docker.io/library/node:22-alpine

stages:
  - build

variables:
  NEXT_TELEMETRY_DISABLED: "1"

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

build:
  stage: build
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
  artifacts:
    name: "build-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 week
    when: on_success
    paths:
      - .next/standalone/
      - .next/static/
      - dist/
